"""Reviewer-grade rubric facts for each Paper-A audit claim (pulled from the result files + the verified claim
inventory + the pre-reg docs). Consumed by build_audit_site.py. Plain ASCII strings only."""

RUBRIC = {
 "A1": {
   "experiment": "Qwen2.5-0.5B/1.5B/3B-Instruct on TriviaQA; logistic probe on frozen band-L hidden states, entity-grouped 5-fold OOF; AUROC of probe vs whether the confident greedy answer was wrong.",
   "prereg": "Yes - c1-frozen-989d14c frozen decision rule + PI-signed pre-flight 2026-06-10 (PASS_preregistered=true)",
   "powered": "Yes",
   "n": "pool 7710; confident 3796; confident-wrong 1715 (0.5B)",
   "effect": "AUROC rises across the Qwen ladder: 0.731 (0.5B) / 0.779 (1.5B) / 0.762 (3B) / 0.802 (14B) / 0.821 (32B); edge over confidence +0.10 to +0.22",
   "test": "rank AUROC entity-grouped OOF; permutation p=0.001; vs preregistered confound floor 0.566",
   "result": "AUROC 0.731, CI [0.715,0.746]; clears floor; perm p=0.001",
   "why": "Clears its preregistered confound floor (0.566) at perm p=0.001 with CI above it across the ladder; PI ratifies POWERED though the file's own EXPLORATORY flag stays set.",
 },
 "A1b": {
   "experiment": "Qwen2.5-1.5B-Instruct on TriviaQA; logistic probe on frozen band-L hidden states, entity-grouped 5-fold OOF; AUROC of probe vs whether the confident greedy answer was wrong.",
   "prereg": "Yes - c1-frozen-989d14c frozen decision rule + PI-signed pre-flight 2026-06-10 (PASS_preregistered=true)",
   "powered": "Yes",
   "n": "confident-wrong 822 (Qwen-1.5B)",
   "effect": "AUROC 0.779; +0.084 over confidence baseline 0.695",
   "test": "rank AUROC entity-grouped OOF; permutation p=0.001; vs preregistered confound floor 0.589",
   "result": "AUROC 0.779, CI [0.76,0.797]; clears floor 0.589; perm p=0.001",
   "why": "The same pre-registered detector at the 1.5B rung of the Qwen ladder; clears its confound floor at perm p=0.001 - this is the detector's scale ladder, not a separate claim.",
 },
 "A1c": {
   "experiment": "Qwen2.5-3B-Instruct on TriviaQA; logistic probe on frozen band-L hidden states, entity-grouped 5-fold OOF; AUROC of probe vs whether the confident greedy answer was wrong.",
   "prereg": "Yes - c1-frozen-989d14c frozen decision rule + PI-signed pre-flight 2026-06-10 (PASS_preregistered=true)",
   "powered": "Yes",
   "n": "confident-wrong 456 (Qwen-3B)",
   "effect": "AUROC 0.762; +0.075 over confidence baseline 0.687",
   "test": "rank AUROC entity-grouped OOF; permutation p=0.001; vs preregistered confound floor 0.563",
   "result": "AUROC 0.762, CI [0.738,0.787]; clears floor 0.563; perm p=0.001",
   "why": "The same pre-registered detector at the 3B rung of the Qwen ladder; clears its confound floor at perm p=0.001.",
 },
 "A1d": {
   "experiment": "Qwen2.5-14B-Instruct on TriviaQA; logistic probe on frozen band-L hidden states, entity-grouped 5-fold OOF; folded from the cloud capture.",
   "prereg": "Yes - c1-frozen-989d14c frozen decision rule + PI-signed pre-flight 2026-06-10 (PASS_preregistered=true)",
   "powered": "Yes", "n": "confident-wrong 186 (Qwen-14B)",
   "effect": "AUROC 0.802; +0.103 over confidence baseline 0.699",
   "test": "rank AUROC entity-grouped OOF; permutation p=0.001; vs preregistered confound floor 0.665",
   "result": "AUROC 0.802, CI [0.76,0.843]; clears floor 0.665; perm p=0.001",
   "why": "The detector at the 14B rung; clears its floor at perm p=0.001 - the ladder keeps clearing as scale rises.",
 },
 "A1e": {
   "experiment": "Qwen2.5-32B-Instruct on TriviaQA; logistic probe on frozen band-L hidden states, entity-grouped 5-fold OOF; folded from the cloud capture.",
   "prereg": "Yes - c1-frozen-989d14c frozen decision rule + PI-signed pre-flight 2026-06-10 (PASS_preregistered=true)",
   "powered": "Yes", "n": "confident-wrong 114 (Qwen-32B)",
   "effect": "AUROC 0.821; +0.221 over confidence baseline 0.600",
   "test": "rank AUROC entity-grouped OOF; permutation p=0.001; vs preregistered confound floor 0.702",
   "result": "AUROC 0.821, CI [0.771,0.865]; clears floor 0.702; perm p=0.001",
   "why": "The top Qwen rung: the detector AUROC is highest here (0.821) and the edge over confidence widens to +0.22 as confidence calibration degrades with scale.",
 },
 "DET27B": {
   "experiment": "gemma-2-27b-it on TriviaQA; logistic probe on frozen band-L hidden states, entity-grouped 5-fold OOF; folded from the cloud capture (cross-family, Google Gemma).",
   "prereg": "Yes - c1-frozen-989d14c frozen decision rule + PI-signed pre-flight 2026-06-10 (PASS_preregistered=true)",
   "powered": "Yes", "n": "confident-wrong 161 (Gemma-2-27B)",
   "effect": "AUROC 0.775; +0.030 over confidence baseline 0.745",
   "test": "rank AUROC entity-grouped OOF; permutation p=0.001; vs preregistered confound floor 0.578",
   "result": "AUROC 0.775, CI [0.733,0.814]; clears floor 0.578; perm p=0.001",
   "why": "A second vendor family (Google Gemma) clears its floor; confidence is already fairly calibrated on this model so the edge is small (+0.03), but the detector still reads the error.",
 },
 "DET24B": {
   "experiment": "Mistral-Small-24B-Instruct-2501 on TriviaQA; logistic probe on frozen band-L hidden states, entity-grouped 5-fold OOF; folded from the cloud capture.",
   "prereg": "No",
   "powered": "No (marginal)", "n": "confident-wrong 85 (Mistral-24B)",
   "effect": "AUROC 0.727; +0.063 over confidence baseline 0.664",
   "test": "rank AUROC entity-grouped OOF; permutation p=0.001; vs confound floor 0.693",
   "result": "AUROC 0.727, CI [0.66,0.787]; does NOT clear floor 0.693",
   "why": "Permutation p=0.001 beats chance, but the AUROC does NOT clear its confound floor (0.727 vs 0.693), n=85 is small, and it was not pre-registered - so it is reported SEPARATELY, not in the powered set (honest scope).",
 },
 "A2": {
   "experiment": "Same c1_detector Qwen ladder (0.5B/1.5B/3B); compares frozen-probe AUROC against the calibrated forced-choice confidence-margin baseline on the same items.",
   "prereg": "Yes - c1-frozen-989d14c frozen decision rule + 2026-06-10 pre-flight (same detector pre-reg)",
   "powered": "No (exploratory)",
   "n": "confident-wrong 1715 / 822 / 456 across 0.5B / 1.5B / 3B",
   "effect": "edge +0.07-0.10 AUROC over confidence (0.731 vs 0.633; 0.779 vs 0.695; 0.762 vs 0.687)",
   "test": "probe AUROC vs confidence-baseline AUROC, entity-grouped OOF (no formal edge-significance test in file)",
   "result": "probe 0.731/0.779/0.762 vs confidence 0.633/0.695/0.687",
   "why": "File flag EXPLORATORY; the local edge is real but the claimed widening to ~0.60 at 32B has no provenance file here, so the scale-trend is unverified.",
 },
 "A3": {
   "experiment": "Clean-room numpy-only re-implementation (imports no sklearn and nothing from the original pipeline) on the same 817-row layerwise features, Qwen-1.5B; per-layer + band logistic probe, grouped-OOF AUROC.",
   "prereg": "Yes - c1-frozen-989d14c detector pre-reg (independent re-impl of the preregistered detector)",
   "powered": "Yes",
   "n": "817 items, 29 layers, dim 1536",
   "effect": "best-layer (L19) AUROC 0.787 logreg; band-L20 0.783; original recorded 0.731",
   "test": "rank AUROC grouped-OOF; permutation p=0.002 (500 perms) at best layer",
   "result": "AUROC 0.787 (L19 logreg), perm p=0.002; reproduces recorded 0.731",
   "why": "Independent re-derivation reproduces the detector at perm p=0.002; the 0.731-vs-0.787 gap is a feature/method choice not a data discrepancy (decomposed in A4).",
 },
 "A4": {
   "experiment": "2x2 reconciliation on identical rows + folds (Qwen-1.5B, 817 items): {kinematic vs raw-band features} x {MLP vs logreg}; plus a four-test de-confound battery (length, structure-shuffle, balance, entity-holdout).",
   "prereg": "Yes - c1-frozen-989d14c detector pre-reg (de-confound battery for the preregistered detector)",
   "powered": "Yes",
   "n": "817 items",
   "effect": "feature effect (raw-minus-kinematic) +0.107 AUROC; length r=0.02; structure-shuffle collapses to 0.502",
   "test": "matched rows+folds AUROC decomposition; de-confound floor 0.56-0.59 from c1_detector",
   "result": "cells kin+MLP 0.668 / kin+logreg 0.696 / raw+MLP 0.796 / raw+logreg 0.783; strongest 0.796",
   "why": "The 0.731-vs-0.787 gap is fully the raw-vs-kinematic feature choice on the same data/splits; length confound r=0.02 and structure-shuffle to chance, so the signal clears the battery.",
 },
 "B1": {
   "experiment": "Risk-coverage across three model families (Qwen-1.5B, Llama, Gemma): entity-grouped detector vs calibrated confidence on a 3000-item pool; danger-zone = the 1500 hardest; selective accuracy at matched coverage 0.9-0.6.",
   "prereg": "No",
   "powered": "Yes",
   "n": "pool 3000/model; danger-zone 1500/model",
   "effect": "+5.6 to +8.5 pp detector-minus-confidence in the danger zone (Qwen +5.7-6.4; Llama +5.8-8.5; Gemma +5.6-7.4)",
   "test": "risk-coverage curve; detector-minus-confidence pp at matched coverage; entity-grouped",
   "result": "Qwen +6.4pp @cov0.7; Llama +8.5pp @cov0.7; Gemma +7.4pp @cov0.7",
   "why": "The internal refusal gate beats calibrated confidence at matched coverage across 3 vendors in the danger zone; the quantified +5.7-6.4pp increment is the contribution.",
 },
 "C1": {
   "experiment": "Qwen-1.5B: commitment-layer (L26) confident-wrong axes for MMLU-trap vs MMLU-ordinary, compared by cosine to reference TQA-trap and ARC-ordinary axes, to test whether the split tracks regime or dataset/style.",
   "prereg": "No",
   "powered": "No (confounded)",
   "n": "TQA-wrong 397; ARC-wrong 357; MMLU-wrong 1232; MMLU trap/ord 410/410",
   "effect": "MMLU-trap cosine 0.055 to TQA-trap vs 0.671 to ARC-ordinary; MMLU-ord 0.933 to ARC-ord vs 0.099 to TQA-trap",
   "test": "cosine alignment of commitment-layer mean axes (descriptive control, no inferential test)",
   "result": "regime_driven = False",
   "why": "regime_driven=False - MMLU-trap aligns with ARC-ordinary (0.671) not TQA-trap (0.055), so the trap/ordinary split tracks dataset/style not regime; this goes to Limitations, NOT the contributions.",
 },
 "C2": {
   "experiment": "Powered regime router, Qwen 0.5B/1.5B/3B: train trap+ordinary LoRA adapters, measure held-out routed-ordinary accuracy via leave-one-source-out (OpenBookQA held out) to test whether the regime representation is capacity-emergent.",
   "prereg": "Yes - PREREG_LAB15_POWERED_ROUTER.md",
   "powered": "No (exploratory)",
   "n": "1013/model (500 trap + 513 ordinary test)",
   "effect": "held-out routed-ordinary 0.012 -> 0.21 -> 0.43 (0.5B->1.5B->3B); leakage proxy falls as size rises",
   "test": "LOSO held-out source accuracy + source-identity-classifier leakage bound",
   "result": "3B LOSO routed-ordinary 0.809 (OpenBookQA-held 0.433); 1.5B 0.735; small-scale near floor",
   "why": "Held-out routed-ordinary accuracy rises with model size (leakage ~ 1/size), so the regime representation is capacity-emergent; small-scale is pattern-matched ignorance.",
 },
 "C3": {
   "experiment": "Anti-transfer matrix, Qwen-1.5B: apply each dataset's confident-wrong steering axis to other datasets at alpha=0.6, measure net correction vs damage with a random-floor control.",
   "prereg": "No",
   "powered": "No (exploratory)",
   "n": "confident-wrong per dataset: TQA 47, ARC 20, OBQA 12, MMLU 18",
   "effect": "scoped trap->ordinary net -0.18 to -0.27; within-regime cross-dataset net median -0.752; old -8.7pp was style-confounded",
   "test": "bootstrap 2000 CI95 per cell; random-floor comparison",
   "result": "TQA->ARC net -0.273, CI [-0.377,-0.182]; verdict STYLE-CONFOUND",
   "why": "STYLE-CONFOUND - ordinary axes do not transfer to other ordinary datasets (every axis is dataset/style-specific), so the -8.7pp headline is the Marin style confound; only the scoped modest harm survives.",
 },
 "C4": {
   "experiment": "Powered regime router (detect->route->correct), Qwen 0.5B/1.5B/3B + Gemma-2-2B + Llama-3B: a learned classifier routes to the trap or ordinary LoRA; router vs best-single-fix accuracy, leakage-controlled (LOSO + source-id bound).",
   "prereg": "Yes - PREREG_LAB15_POWERED_ROUTER.md",
   "powered": "Yes",
   "n": "1013/model (500 trap + 513 ordinary)",
   "effect": "+4.7 to +10.5 pp over best single fix (Qwen .5B +10.5 / 1.5B +4.7 / 3B +6.2; Gemma-2B +7.1; Llama-3B +5.3)",
   "test": "McNemar p<0.001 two-sided + bootstrap 95% CI on the gain (excludes 0)",
   "result": "Gemma-2B router 0.802 vs best-single 0.731 = +7.1pp, boot95 [5.1,9.1], McNemar p<0.001",
   "why": "Router beats best-single-fix on every model with bootstrap CIs excluding 0 and McNemar p<0.001 under LOSO + source-identity leakage control; ordering router>best-single>base holds throughout.",
 },
 "D1": {
   "experiment": "Regime-matched governance LoRA on Qwen-1.5B (r=8, lr=1e-4, 900 steps): train a correction adapter, then evaluate on HELD-OUT categories never seen in training; base vs LoRA accuracy.",
   "prereg": "No",
   "powered": "Yes",
   "n": "189 held-out-category items",
   "effect": "+29.1 pp (base 0.561 -> LoRA 0.852) on held-out categories",
   "test": "held-out-category accuracy lift (held-out generalization design)",
   "result": "base 0.561 -> LoRA 0.852, lift +0.291",
   "why": "The LoRA lifts categories it never trained on (+29.1pp held-out), so the regime-matched correction generalizes and can be baked into weights - that held-out generalization is the increment over standard adapters.",
 },
 "D2": {
   "experiment": "Continuous commitment-layer steering, Qwen-1.5B (band-L17, alpha=0.6, block layers 12-23): inject the confident-wrong axis at the commitment layer and measure flip rate / entropy on a 40-item pool.",
   "prereg": "No",
   "powered": "Yes",
   "n": "40-item pool (Qwen-1.5B)",
   "effect": "single-layer flip 1.0, continuous-block flip 1.0; net +0.233 at the commitment layer",
   "test": "flip-rate with entropy/maxprob readout (descriptive)",
   "result": "single-layer flip 1.0 (entropy 0.416, maxprob 0.863); continuous flip 1.0",
   "why": "At <=3B the commitment-layer steer flips the answer reliably (flip 1.0); this is steering tooling (ITI/RepE-class), powered at the steerable scale.",
 },
 "D2b": {
   "experiment": "Continuous-steer scale ladder, Qwen-1.5B vs 3B (and 14B per the inventory): measure net steering effect at each scale to test monotone attenuation; 1.5B single-layer flips, 3B single-layer fails.",
   "prereg": "No",
   "powered": "Yes",
   "n": "40-item pool (1.5B) / 37 (3B)",
   "effect": "non-monotone: +0.158 @1.5B / -0.045 @3B / +0.179 @14B",
   "test": "flip-rate across the scale ladder (descriptive non-monotonicity)",
   "result": "1.5B single-layer flip 1.0; 3B single-layer flip 0.0 (continuous 1.0); reverses then recovers",
   "why": "The steering effect is non-monotone in scale (1.5B flips single-layer, 3B does not, 14B recovers), refuting a simple attenuation-with-scale story - a bounding negative.",
 },
 "E1": {
   "experiment": "INT-2 orthogonalization across three model families, Gemma-2-2B (alpha=1.2) + Llama-3B + Qwen-1.5B: corrupt right answers along the soft gold->lure axis, remove K=5 band PCs, and test if corruption survives vs an isotropic control.",
   "prereg": "No",
   "powered": "No (exploratory)",
   "n": "Gemma right/wrong-steer 60/52; orth arm wrong 45",
   "effect": "corrupt survives orthogonalization on all 3: Gemma 0.73 vs iso 0.37; Llama 0.96 vs 0.08; Qwen-1.5B 0.92 vs 0.35",
   "test": "rate with bootstrap CI95; orthogonalized vs isotropic non-overlap",
   "result": "Gemma corrupt orth 0.73 CI[0.64,0.82] vs iso 0.37 CI[0.27,0.47] -> survives",
   "why": "Corruption survives orthogonalization above the isotropic control on all 3 families, so corruption rides the specific gold<->lure direction cross-family.",
 },
 "E2": {
   "experiment": "The same INT-2 orthogonalization arms across three model families (Gemma-2-2B / Llama-3B / Qwen-1.5B): test the rescue arm (lure->gold) and whether rescue survives orthogonalization, for corruption/rescue asymmetry and rescue subspace-specificity.",
   "prereg": "No",
   "powered": "No (exploratory)",
   "n": "Gemma wrong-steer 52/45; Llama wrong 20",
   "effect": "rescue ~0 in all conditions on all 3 (asymmetry cross-family); rescue does NOT survive orthogonalization (219x-specific)",
   "test": "rescue-rate bootstrap CI95; orthogonalized vs isotropic",
   "result": "Gemma rescue soft 0.0 / iso 0.019; rescue collapses",
   "why": "Rescue collapses (~0) on all 3 families so the asymmetry replicates, but rescue does not survive orthogonalization anywhere and is band/alpha-sensitive - the rescue-needs-the-dominant-subspace mechanism is Qwen-only/exploratory.",
 },
 "F1": {
   "experiment": "Integrated governor end-to-end, Qwen-1.5B + Gemma-2-2B: base model vs the full detect->route->correct->refuse governor accuracy on the 1013-item trap+ordinary test.",
   "prereg": "Yes - PREREG_LAB15_POWERED_ROUTER.md",
   "powered": "Yes",
   "n": "1013/model (500 trap + 513 ordinary)",
   "effect": "+13 to +20.4 pp governed-vs-base (Qwen-1.5B 0.608->0.738 +13.0; Gemma-2B 0.597->0.802 +20.4)",
   "test": "McNemar p<0.001 + bootstrap CI on the router-vs-best-single-fix gain (excludes 0)",
   "result": "Gemma base 0.597 -> router 0.802 (+20.4); Qwen 0.608 -> 0.738 (+13.0)",
   "why": "The governed pipeline beats base by +13 to +20.4pp matching the powered base->router span, with the same leakage controls and CI-excludes-0 statistics as C4.",
 },
 "F2": {
   "experiment": "Benchmark governor cross-transfer: a small-model commitment-layer probe (layers 19,22,24) trained per-benchmark and pooled across MMLU/ARC/OpenBookQA/etc., plus train-on-others/test-held-out transfer AUROC.",
   "prereg": "No",
   "powered": "No (moderate)",
   "n": "200/benchmark; ~7 benchmarks pooled",
   "effect": "pooled AUROC 0.713; per-benchmark 0.737-0.814; transfer 0.56-0.75",
   "test": "rank AUROC, bootstrap CI95, permutation p=0.001 per benchmark and pooled",
   "result": "pooled AUROC 0.713, CI [0.685,0.738]; transfer e.g. CommonsenseQA 0.749, HellaSwag 0.563",
   "why": "Pooled 0.713 is below the file's own 0.8 task-general bar; with transfer down to 0.56 it is MODERATE transfer, not the task-general claim the file required.",
 },
 "G1": {
   "experiment": "Per-layer participation-ratio PR(J) of the Jacobian, Qwen2.5-0.5B; measures PR input-invariance. The preprint/powered run gives PR ~400.3 (wrong) vs 396.8 (right) and the endpoint-detector AUROC, paired with the bounded-norm/rank theorem.",
   "prereg": "No",
   "powered": "No (prediction + empirical; theorem reviewed and accepted with fixes)",
   "n": "smoke 10 prompts, 24 layers (preprint PR run 400.3 vs 396.8)",
   "effect": "PR difference 0.90% (400.3 vs 396.8); endpoint-detector AUROC 0.531",
   "test": "PR-mean-by-layer; AUROC of the endpoint detector vs correctness",
   "result": "preprint PR 400.3 vs 396.8 = 0.90%, AUROC 0.531 (~chance)",
   "why": "PR(J) is near-invariant to whether the answer is wrong (0.90% gap, AUROC 0.531), so unsupervised endpoint detectors and SE are predicted blind; the theorem (needs rank o(d) AND bounded norm) was independently reviewed - a gap was caught and fixed, then accepted - and is not yet re-integrated.",
 },
 "G2": {
   "experiment": "Mechfloor consolidated, Qwen-0.5B (band-17): confidence-matched (|margin|-binned) AUROC of hidden-state dispersion (trace, mean-pairwise-cos-distance) separating confident-wrong 'trap' from correct twins; ladder 0.5B/1.5B/3B/Llama-3B.",
   "prereg": "No",
   "powered": "No (exploratory / inconclusive)",
   "n": "50/class (correct / trap / ignorance)",
   "effect": "trace/mpcd AUROC 0.407/0.409 (0.5B); ~0.48-0.50 across the ladder - no separating signal",
   "test": "confidence-binned rank AUROC (margin held fixed by binning)",
   "result": "0.5B trace AUROC 0.407, mpcd 0.409 (twins null)",
   "why": "n=50/class is underpowered to assert absence - dispersion shows no separating signal (AUROC ~0.5, confidence-matched), but a failure-to-find at n=50 cannot be called a proven null, so it stays inconclusive/exploratory.",
 },
 "G3": {
   "experiment": "Semantic entropy (Farquhar NLI-clustered, K=8 sampled generations, roberta-large-mnli) on Gemma-2-27B over 800 TruthfulQA items; AUROC of SE vs whether the greedy answer was wrong, plus a confident-wrong vs ignorance split; TriviaQA positive control 0.774.",
   "prereg": "Yes - PREREG_FARQUHAR_SEMANTIC_ENTROPY_v1.md",
   "powered": "Yes",
   "n": "800 (Gemma-27B); confident-wrong 228, ignorance 226; 5 models / 3 families overall",
   "effect": "TruthfulQA AUROC 0.476-0.561 (all CI upper <0.65) vs TriviaQA control 0.774 = double dissociation",
   "test": "rank AUROC with bootstrap CI95; confident-wrong vs ignorance split",
   "result": "Gemma-27B SE AUROC 0.527, CI [0.489,0.565]; confident-wrong 0.514 [0.469,0.556]",
   "why": "SE is at-chance on TruthfulQA confident errors (CI upper 0.565 < 0.65 across 5 models/3 families) yet 0.774 on TriviaQA ignorance - a clean double dissociation, the strongest measured leg.",
 },
 "G4": {
   "experiment": "Cross-task SE inversion, Qwen-1.5B: open-generation NLI semantic entropy joined against an INDEPENDENT layerwise forced-choice error label; AUROC of SE vs forced-choice-wrong, n=250.",
   "prereg": "Yes - PREREG_FARQUHAR_SEMANTIC_ENTROPY_v1.md (SE measurement pre-reg)",
   "powered": "Yes",
   "n": "250 (forced-choice wrong 115, correct 135; double-wrong 80)",
   "effect": "AUROC 0.443 (below chance = inversion); 56.5% of forced-choice-wrong sit in the low-SE cluster",
   "test": "rank AUROC with bootstrap CI95 (non-circular: the SE task differs from the forced-choice task)",
   "result": "AUROC 0.443, CI [0.375,0.516]; median SE forced-choice-wrong 1.494 ~ correct 1.667",
   "why": "Open-gen SE is blind-to-inverted on the independent forced-choice confident-error basin (0.443, 56.5% of wrong in the low-SE cluster), confirming SE blindness non-circularly; the caveat is the adversarial-lure (Kalai) design.",
 },
 "H1": {
   "experiment": "Powered window-patching, Qwen2.5-1.5B/3B/7B/14B/32B: patch the commitment-band (layers 12-23) of clean-true runs and measure the flip-to-confident-FALSE rate; tests that the confident-error basin is reachable on-manifold and persists with scale.",
   "prereg": "No",
   "powered": "Yes",
   "n": "clean n: 42 (1.5B) / 162 (3B) / 230 (7B) / 250 (14B) / 248 (32B)",
   "effect": "window-patch flip ~0.95-1.0 at every scale (1.5B 0.952; 3B-32B 1.0)",
   "test": "Wilson 95% CI on the flip rate (excludes coin-flip at every scale)",
   "result": "1.5B flip 0.952, Wilson [0.842,0.987]; 14B/32B flip 1.0, Wilson [0.985,1.0]",
   "why": "Window-patch flips to confident-false ~0.95-1.0 at every scale 1.5B->32B with Wilson CIs excluding chance, so the wrong-answer basin exists and is patching-reachable on-manifold across scale (Akarlar's basin extended).",
 },
 "I1": {
   "experiment": "Probability-flux probe, Qwen-1.5B (band-L24): measure the probability-current ratio rho_Q on TQA-traps (n=817) vs GSM8K-reasoning (n=6000) to test for a capacity cliff in the non-equilibrium flux.",
   "prereg": "No",
   "powered": "No (exploratory)",
   "n": "TQA-trap 817; GSM8K 6000",
   "effect": "no accuracy cliff; flux rho_Q 0.177 (TQA) vs 0.273 (GSM8K), propagator radius 0.776 vs 0.949",
   "test": "bootstrap CI95 on rho_Q (CIs non-overlapping between regimes)",
   "result": "TQA rho_Q 0.177 [0.163,0.182]; GSM8K rho_Q 0.273 [0.262,0.283]; CIs separated",
   "why": "Flux varies with cognitive regime (reasoning > trap, non-overlapping CIs) with no accuracy cliff across the sweep - a bounding NULL on the capacity-cliff hypothesis; exploratory.",
 },
 "I2": {
   "experiment": "Same probability-flux / substrate-dynamics probe, asking whether the dynamics are hallucination-specific or generic (contraction ~0.829, rotation ~0.76 non-discriminative AUROC 0.44); N=1 model.",
   "prereg": "No",
   "powered": "No (exploratory)",
   "n": "N=1 model (TQA 817 / GSM8K 6000 conditions)",
   "effect": "substrate generic: contraction 0.829, rotation 0.76 non-discriminative (AUROC 0.44); 2 dramatic readings retired",
   "test": "rank AUROC for discrimination (non-discriminative); descriptive flux comparison",
   "result": "rho_Q regime-varying but generic; rotation AUROC 0.44 (not hallucination-specific)",
   "why": "Substrate dynamics track regime/computation generically, not a hallucination-specific signature (rotation AUROC 0.44), and prior dramatic readings were retired - a bounding NULL at N=1, exploratory.",
 },
 "SAE": {
   "experiment": "SAE confident-error probe, Gemma-2-2B with the gemma-scope-2b-pt-res 16k SAE at commitment band L12 (n=817): unsupervised SAE reconstruction-error as an anomaly score vs a supervised probe vs a per-feature oracle, on confident-wrong vs correct.",
   "prereg": "No",
   "powered": "No (exploratory; corroborates the bound)",
   "n": "817 (confident-wrong 260, ignorance 258, correct 299)",
   "effect": "unsupervised recon-error is BLIND: confident-wrong 81.19 ~ correct 81.18; supervised SAE-feature AUROC only 0.562",
   "test": "5-fold OOF AUROC (supervised / oracle) + mean recon-error contrast (unsupervised)",
   "result": "recon-err confident-wrong 81.194 vs correct 81.181 (~identical); supervised 0.562; oracle 0.524",
   "why": "The unsupervised SAE reconstruction error is identical for confident-wrong and correct (81.19 vs 81.18) and the supervised SAE-feature AUROC is only 0.56 - the dictionary-learning readout is endpoint-blind to confident error, corroborating the bound.",
 },
 "DET8B": {
   "experiment": "Frozen-state confident-error detector on Llama-3.1-8B-Instruct (folded from the cloud capture): logistic probe on band hidden states, entity-grouped OOF, AUROC vs confident-wrong; with the selective-accuracy / refusal curve.",
   "prereg": "Yes - c1-frozen-989d14c frozen decision rule + 2026-06-10 pre-flight (PASS_preregistered=true)",
   "powered": "Yes",
   "n": "pool 7710; confident 3759; confident-wrong 591; entity-groups 3222",
   "effect": "AUROC 0.849; +0.136 over confidence baseline 0.713; selective acc 0.961 @50% coverage vs 0.843 random",
   "test": "rank AUROC entity-grouped OOF; permutation p=0.001; vs confound floor 0.698",
   "result": "AUROC 0.849, CI [0.83,0.866]; perm p=0.001; clears floor 0.698",
   "why": "The detector clears its preregistered confound floor (0.698) at AUROC 0.849, perm p=0.001, with 0.961 selective accuracy at 50% coverage - it scales up to an 8B cross-family model.",
 },
 "RX3B": {
   "experiment": "Powered regime router on Qwen2.5-3B-Instruct: a learned regime classifier (acc 0.997) routes to the trap/ordinary LoRA; router vs best-single-fix accuracy, leakage-controlled (LOSO + source-id classifier 0.986), n=1013.",
   "prereg": "Yes - PREREG_LAB15_POWERED_ROUTER.md",
   "powered": "Yes",
   "n": "1013 (500 trap + 513 ordinary)",
   "effect": "+6.2 pp over best single fix (router 0.832 vs trap-LoRA 0.770); base 0.750",
   "test": "McNemar p<0.001 (discordant 81 vs 18) + bootstrap 95% CI [4.3,8.2] (excludes 0)",
   "result": "router 0.832 vs best-single 0.770 = +6.2pp, boot95 [4.3,8.2], McNemar p<0.001",
   "why": "On Qwen-3B the router beats best-single-fix by +6.2pp with bootstrap CI excluding 0 and McNemar p<0.001 under LOSO + source-id leakage control (0.986) - the highest-capacity Qwen router point, magnitude confirmatory.",
 },
}
